-- 스키마와 테이블 생성
CREATE DATABASE IF NOT EXISTS study_db;

USE study_db;

-- DEPT 테이블 생성
CREATE TABLE IF NOT EXISTS DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);

-- DEPT 초기 데이터 삽입
INSERT IGNORE INTO DEPT (DEPTNO, DNAME, LOC) VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT IGNORE INTO DEPT (DEPTNO, DNAME, LOC) VALUES (20, 'RESEARCH', 'DALLAS');
INSERT IGNORE INTO DEPT (DEPTNO, DNAME, LOC) VALUES (30, 'SALES', 'CHICAGO');
INSERT IGNORE INTO DEPT (DEPTNO, DNAME, LOC) VALUES (40, 'OPERATIONS', 'BOSTON');


-- 비관적 락을 위한 테이블
CREATE TABLE IF NOT EXISTS PESSIMISTIC_REWARD_COUNT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_TYPE CHAR(1) NOT NULL,  -- 보상 그룹 (A, B, C, D)
    COUNT INT NOT NULL,           -- 남은 보상 횟수
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 행 생성 시 타임스탬프
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 행 수정 시 타임스탬프
);

-- 낙관적 락을 위한 테이블
CREATE TABLE IF NOT EXISTS OPTIMISTIC_REWARD_COUNT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GROUP_TYPE CHAR(1) NOT NULL,  -- 보상 그룹 (A, B, C, D)
    COUNT INT NOT NULL,           -- 남은 보상 횟수
    VERSION INT DEFAULT 1,        -- 낙관적 락을 위한 버전 필드
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- 행 생성 시 타임스탬프
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- 행 수정 시 타임스탬프
);

-- 캐시 리워드 초기 데이터 삽입 (중복 방지)
INSERT IGNORE INTO PESSIMISTIC_REWARD_COUNT (GROUP_TYPE, COUNT) VALUES ('A', 100), ('B', 10), ('C', 10), ('D', 5);
INSERT IGNORE INTO OPTIMISTIC_REWARD_COUNT (GROUP_TYPE, COUNT, VERSION) VALUES ('A', 100, 1), ('B', 10, 1), ('C', 10, 1), ('D', 5, 1);
